# Generated by Django 3.2 on 2022-12-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
